### ISSUE TITLE
Could not find a version that satisfies the requirement transfer_lab

### ISSUE THREAD

**Issue by yuanlinping** [qhanson/translucent-image-recolor#1]
I got an error when compiling:
`Traceback (most recent call last):
  File "GUI_hm_dark_style.py", line 16, in <module>
    import transfer_lab
ImportError: No module named 'transfer_lab'`

However, I could not install 'transfer_lab' via pip. So my question is where I could get this module. If this module is written by yourselves, could you please release it?

Thank you in advance :)

**Comment by qhanson** [comment]
Sorry for the late update. 
However, I have not tested it on other computers.
